services:
  dev:
    build:
      context: docker
      target: dev
    volumes:
      - type: bind
        source: .
        target: /var/app
      - dev-egg-info:/var/app/src/dummy.egg-info
    expose:
      - "5000"
    ports:
      - "5000:5000"
    command: sh -c "pipx inject --editable flask . && flask --app dummy run --host 0.0.0.0 --port 5000 --reload --debug --debugger"

  prod:
    build:
      context: docker
      target: prod
    volumes:
      - type: bind
        source: .
        target: /var/app
      - prod-egg-info:/var/app/src/dummy.egg-info
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      LOGGING_LEVEL: "info"
    command: sh -c "pipx inject flask . && gunicorn --workers=2 --bind 0.0.0.0:8000 'dummy:app' --log-level ${LOGGING_LEVEL}"

volumes:
  dev-egg-info:
  prod-egg-info: